### ISSUE TITLE
Conflict with Easyblog YOOtheme element

### ISSUE THREAD

**Issue by bastiaanc** [forrestkirby/herzogdupont-joomla#15]
Fatal error: Cannot declare class SettingsListener, because the name is already in use in /home/web92fss/domains/fairchildfun.com/public_html/plugins/system/yoothemeeasyblog/modules/elements/src/settings.php on line 1
[plg_yootheme_easyblog.zip](https://github.com/forrestkirby/herzogdupont-joomla/files/7839707/plg_yootheme_easyblog.zip)
8

**Comment by forrestkirby** [comment]
Hi bastiaanc,

thanks for bringing this to my attention. This shall be fixed in the next release. Please note that EasyBlog should use a namespace or a prefix for their class names, too. Else, you will get the same error with any other extension using the class names from the [example module](https://github.com/yootheme/example-module).

Kind regards
