### ISSUE TITLE
Easyblog element for YOOtheme

### ISSUE THREAD

**Issue by bastiaanc** [forrestkirby/herzogdupont-joomla#17]
**D
<img width="2112" alt="Screenshot 2022-02-21 at 09 59 49" src="https://user-images.githubusercontent.com/9219295/154922995-bb7d5a67-be96-4411-b886-eab68aa3e404.png">
escribe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS [e.g. iOS, Windows 10]
 - YOOtheme Pro Version [e.g. 2.4.0]
 - Herzog Dupont for YOOtheme Pro Version [e.g. 1.0.0]

**Additional context**

**Comment by forrestkirby** [comment]
Hi bastiaanc,

this is a duplicate to #15 which has already been fixed by [this commit](https://github.com/forrestkirby/herzogdupont-joomla/commit/b6b1e8d8bc9022abe9b582ec09e87b5155f0b3f1). The fix is included in the release [1.6.3](https://github.com/forrestkirby/herzogdupont-joomla/releases/tag/v1.6.3). Please update and let me know whether the issue persists. Thank you.

Kind regards
Thomas

**Comment by bastiaanc** [comment]
Thanks, it works :-)
