### ISSUE TITLE
HD Image comparison add a 20px margin left and right

### ISSUE THREAD

**Issue by PixedBo** [forrestkirby/herzogdupont-joomla#19]
**Describe the bug**
The element works fine. If i have only one image it has no margin, when i add the 2nd image a 20px margin is added bot left and right of the image. Both images are the same size

**To Reproduce**
Use the element in a half left column
Add the first image
Add the second image

**Expected behavior**
No margin left and right

**Screenshots**

Fist image only:

![img1](https://user-images.githubusercontent.com/12549961/157701720-be43f874-ef6e-416e-8e28-b0b70695a01b.JPG)

With 2nd image:

![img2](https://user-images.githubusercontent.com/12549961/157701772-b2389643-915d-4ca5-831a-7bcad1f476d9.JPG)

**Client (please complete the following information):**
latest versione of joomla4, Yootheme and HD plugin

**Comment by forrestkirby** [comment]
Hi PixedBo,

it is on purpose that there is a left and right margin on the image, because the slider exceeds the bounds of the image but it should still be visible. If you removed the margin, the slider might not be fully visible as indicated by the screenshots below.

![](https://fuse.herzog-dupont.de/images/Screenshot_2022-03-10_223209.png)

![](https://fuse.herzog-dupont.de/images/Screenshot_2022-03-10_223248.png)

If you want to remove the margin nevertheless, you should be able to achieve this by adding the following at *Advanced → CSS*:

```css
.el-element .hd-image-comparison {
    margin: 0 !important;
}
```

Kind regards
Thomas

**Comment by PixedBo** [comment]
Nice, thank you!
