### ISSUE TITLE
How to start HD Lottie animation programmatically?

### ISSUE THREAD

**Issue by rvalitov** [forrestkirby/herzogdupont-joomla#24]
Hi! I have a lottie animation that I want so start programmatically. How can I access the HD Lottie object to play the animation?

**Comment by forrestkirby** [comment]
Hi rvalitov,

thanks for pointing this out. You should be able to simply use `lottie.play()` to play and `lottie.pause()` to pause all animations on a page. But currently, there is no way to target a single animation if you have multiple animations as the animation name is generated on the fly. A field to provide an animation name which you can use to target a single animation by calling `lottie.play('mylottie')` or `lottie.pause('mylottie')` will be added with [this commit](https://github.com/forrestkirby/herzogdupont-joomla/commit/e6e4172d1e1707be27ab2b300d44a2e25cbe33af). Let me know whether this fits your needs.

Best regards

**Comment by rvalitov** [comment]
Thank you so much! Do you plan to publish a new release with this update?

**Comment by rvalitov** [comment]
One more comment. Calling simply `lottie.play` triggers error that `lottie.play` function is not found. It's required to be referenced as `window.lottie.play`.

**Comment by forrestkirby** [comment]
> Do you plan to publish a new release with this update?

Yes, but I am awaiting YOOtheme Pro 2.8 as I expect this version to require some updates for custom elements that I’d like to pack into the same release.

> One more comment. Calling simply lottie.play triggers error that lottie.play function is not found. It's required to be referenced as window.lottie.play.

I’m sorry, but I could not reproduce this issue. `lottie` should be defined as a global variable and, thus, window can be omitted (except for certain edge cases). If the issue also occurs when adding lottie.js via an HTML element (see the [Lottie for Web GitHub repo](https://github.com/airbnb/lottie-web) for details) instead of using this plugin, it’is likely to be an issue of lottie rather than this plugin.

Best regards

**Comment by forrestkirby** [comment]
1.7.0 hasfinally be released which includes the above mentioned commit. I’m sorry for the delay, I was waiting for YOOtheme Pro 3.0 to be released.

https://github.com/forrestkirby/herzogdupont-joomla/releases/tag/v1.7.0
