### ISSUE TITLE
Toggle - uk-offcanvas display

### ISSUE THREAD

**Issue by ChrisBo71** [forrestkirby/herzogdupont-joomla#32]
Hi there

Could you lease advise whether the HD Toggle for Joomla / Zoo / Yootheme builder Pro can be set up so the toggled element will appear in offcanvas position. If so, please help to set it up.
Thank you

Chris

**Comment by forrestkirby** [comment]
Hi Chris,

do you want to toggle the whole offcanvas or only an element within or both at the same time? Is the toggle button located within the offcanvas layout?

Kind regards

**Comment by ChrisBo71** [comment]
Hi Guys

 

Did not expect such a prompt response.

Thank you!

 

Best way to explain is if you have a look at the current set up.

 

SYSTEM

Joomla 3.10.11

Zoo 4

YT Builder Pro latest

PLUS your element HD Toggle

 

PRESENT SET UP:

Currently HD Toggle toggles a section containing Zoolanders filter. 

This works ONLY on MOBILES.

It is a bit cumbersome though when it comes to scrolling down and choosing options to filter by.

 

DIRECT LINK to the present setup (MOBILE view only): 

https://wakacje24.uk/wakacje-wyloty-uk

Please use button “FILTROWANIE”

 

OBJECTIVES

What I would like to achieve is to show the whole section with filters similarly to a mobile menu covering the whole viewpoint. Off canvass.

This way it would be more user friendly.

Also a CLOSE X button would be desirable.

 

EXAMPLE – see John Lewis website and filters (also MOBILE version only)

DIRECT LINK: https://www.johnlewis.com/browse/men/new-in-mens-clothing-shoes-accessories/_/N-ebk

 

 

If you could help with the above, it would be more tan appreciated.

I have already spent on this a couple of hours.

(also trying to implement the ULKIT off=canvass / of-canvass-bar / standard button version with no success)

 

Kind regards

Chris

**Comment by ChrisBo71** [comment]
Hi Guys any chance for a piece of advice as per my previous emails?

 

Chris

**Comment by forrestkirby** [comment]
Thank you for providing these details. Using the toggle element, you cannot or can not easily trigger the offcanvas animation of an element that the UIkit offcanvas component is bound to. While it is probably possible to achieve a similar effect to a section using the toggle element instead of the UIkit offcanvas component, it would require some CSS to correctly position that section and probably also to adjust the animation accordingly. Therefore, I would suggest to use the offcanvas component rather than the toggle element as follows:

- add an HTML element to your layout that will contain the following code to display a button to show/hide the offcanvas (the HTML element must not be within the section that will contain the offcanvas layout)

    ```html
    <button uk-toggle="target: #myoffcanvas" type="button" class="uk-button uk-button-default">show</button>
    ```

- add a section that will contain the offcanvas layout or use an existing one and set the ID `myoffcanvas` in the advanced settings
- add an HTML element to the section that will contain the offcanvas layout with the following content

    ```html
    <button class="uk-offcanvas-close" type="button" uk-close></button>
    <script>
    UIkit.util.ready(()=> {
        let myOffcanvas = document.getElementById('myoffcanvas');
        myOffcanvas.children[0].classList.add('uk-offcanvas-bar');
        UIkit.offcanvas(myOffcanvas);
    });
    </script>
    ```

Please let me know whether this approach suits your needs or whether you would prefer to use the toggle element.

Kind regards
