### ISSUE TITLE
Flip for YTP

### ISSUE THREAD

**Issue by mamboklaus** [forrestkirby/herzogdupont-joomla#36]
First, it works great and is exactly what my client may wants!
Great work!
http://kfuchs.eu/#flip
Is there any way to filter those single flip cards?
As you can se in my demo link, we will have around 100 flip cards, I would like to sort it wuth a filter menu for (example) Food, entertainment, bars, music....

Any idea how to create this filter?

Thanks Klaus

**Comment by forrestkirby** [comment]
Hi Klaus,

thanks for your kind feedback! There is no such option in the element and it would require a different kind of element to add this functionality, i. e. instead of a basic element like the Panel element you would need to create a multiple items element like the Grid element (in other words, you would need to create a Flipcard Grid element). I do not have any plans to do so at the moment.

As a workaround, you could try the following steps. It is not exactly the same as in the Grid element, but maybe it gives you a starting point:

1. create a new section with the ID `hd-flip-filter`
2. add a row with an HTML element with the following content

  ```html
  <script>
      UIkit.util.ready(_ => {
          UIkit.filter('#hd-flip-filter', {target: '.hd-flip-filter-items'});
      });
  </script>
  <ul class="uk-subnav uk-subnav-pill">
      <li class="uk-active" uk-filter-control><a href="#">All</a></li>
      <li uk-filter-control=".white"><a href="#">White</a></li>
      <li uk-filter-control=".blue"><a href="#">Blue</a></li>
      <li uk-filter-control=".black"><a href="#">Black</a></li>
  </ul>
  ```

3. add a row with the ID `hd-flip-filter-items` and choose the column layout of your need, e. g. *Quarters*
4. to this row, add your flipcard elements, only **one per column**
5. add one or more classes to each column, e. g. `blue` or `white` or `blue white`; this class8es) will serve as filter tag(s)
6. repeat steps 3–5 for as many rows and flipcard elements as you need

Here is a demo layout you can download: [Demo Layout](https://yootheme.herzog-dupont.de/downloads/layouts/flipcards-with-filter-issue-36.json)

[Screencast](https://app.screencast.com/Y9NAcB6jenDKO)

Learn more about the UIkit filter component here: [UIkit filter](https://getuikit.com/docs/filter)

Best regards

**Comment by mamboklaus** [comment]
Wow!
Super.
Thanks – it works and I understand😊

klaus

Von: forrestkirby ***@***.***>
Datum: Donnerstag, 2. Februar 2023 um 18:32
An: forrestkirby/herzogdupont-joomla ***@***.***>
Cc: mamboklaus ***@***.***>, Author ***@***.***>
Betreff: Re: [forrestkirby/herzogdupont-joomla] Flip for YTP (Issue #36)

Hi Klaus,

thanks for your kind feedback! There is no such option in the element and it would require a different kind of element to add this functionality, i. e. instead of a basic element like the Panel element you would need to create a multiple items element like the Grid element (in other words, you would need to create a Flipcard Grid element). I do not have any plans to do so at the moment.

As a workaround, you could try the following steps. It is not exactly the same as in the Grid element, but maybe it gives you a starting point:

  1.  create a new section with the ID hd-flip-filter
  2.  add a row with an HTML element with the following content

<script>



    UIkit.util.ready(_ => {



        UIkit.filter('#hd-flip-filter', {target: '.hd-flip-filter-items'});



    });



</script>



<ul class="uk-subnav uk-subnav-pill">



    <li class="uk-active" uk-filter-control><a href="#">All</a></li>



    <li uk-filter-control=".white"><a href="#">White</a></li>



    <li uk-filter-control=".blue"><a href="#">Blue</a></li>



    <li uk-filter-control=".black"><a href="#">Black</a></li>



</ul>

  1.  add a row with the ID hd-flip-filter-items and choose the column layout of your need, e. g. Quarters
  2.  to this row, add your flipcard elements, only one per column
  3.  add one or more classes to each column, e. g. blue or white or blue white; this class8es) will serve as filter tag(s)
  4.  repeat steps 3–5 for as many rows and flipcard elements as you need

Here is a demo layout you can download: Demo Layout<https://yootheme.herzog-dupont.de/downloads/layouts/flipcards-with-filter-issue-36.json>

Screencast<https://app.screencast.com/Y9NAcB6jenDKO>

Learn more about the UIkit filter component here: UIkit filter<https://getuikit.com/docs/filter>

Best regards
