### ISSUE TITLE
Lottie Json didn´t works

### ISSUE THREAD

**Issue by ProjektOliver** [forrestkirby/herzogdupont-joomla#67]
**Describe the bug**
When I use the Lottie Json file, nothing is displayed. Everything works with the link. What could be the reason?

This is my file:
[Buchen40.json](https://github.com/user-attachments/files/16244786/Buchen40.json)

**Client (please complete the following information):**
Joomla 5.1.2
YOOtheme Version 4.4.5

**Comment by forrestkirby** [comment]
The animation works fine on my end, see https://app.screencast.com/leGcE7aTKtrCs

**Comment by forrestkirby** [comment]
I think I now understood what you mean. The issue is that the animation does not display at first in the customizer preview when added, but only after save & reload or in the frontend. I suspect that this is caused by a change in the behavior of the customizer. I will discuss this with the YOOtheme developers. Thanks for reporting.

Best regards

**Comment by forrestkirby** [comment]
https://yootheme.com/support/question/166177
